services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    networks:
      rede_interna:
    depends_on:
      - database

  database:
    image: mariadb:11
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    ports:
      - "3307:3306"
    networks:
      rede_interna:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    networks:
      rede_interna:
    depends_on:
      - database

networks:
  rede_interna:
